# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jobs.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Jobs(object):
    def setupUi(self, Jobs):
        Jobs.setObjectName("Jobs")
        Jobs.resize(248, 317)
        self.jobList = QtWidgets.QListView(Jobs)
        self.jobList.setGeometry(QtCore.QRect(20, 50, 211, 231))
        self.jobList.setObjectName("jobList")
        self.label = QtWidgets.QLabel(Jobs)
        self.label.setGeometry(QtCore.QRect(20, 10, 171, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Jobs)
        self.label_2.setGeometry(QtCore.QRect(190, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.goBackButton = QtWidgets.QPushButton(Jobs)
        self.goBackButton.setGeometry(QtCore.QRect(80, 290, 75, 23))
        self.goBackButton.setObjectName("goBackButton")

        self.retranslateUi(Jobs)
        QtCore.QMetaObject.connectSlotsByName(Jobs)

    def retranslateUi(self, Jobs):
        _translate = QtCore.QCoreApplication.translate
        Jobs.setWindowTitle(_translate("Jobs", "Jobs Found"))
        self.label.setText(_translate("Jobs", "The following jobs were found for:"))
        self.label_2.setText(_translate("Jobs", "<skill>"))
        self.goBackButton.setText(_translate("Jobs", "Go Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Jobs = QtWidgets.QDialog()
    ui = Ui_Jobs()
    ui.setupUi(Jobs)
    Jobs.show()
    sys.exit(app.exec_())
