# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'top_jobs.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_top_jobs(object):
    def setupUi(self, top_jobs):
        top_jobs.setObjectName("top_jobs")
        top_jobs.resize(301, 320)
        self.label = QtWidgets.QLabel(top_jobs)
        self.label.setGeometry(QtCore.QRect(20, 0, 271, 41))
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(top_jobs)
        self.tableWidget.setGeometry(QtCore.QRect(20, 40, 256, 261))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(125)

        self.retranslateUi(top_jobs)
        QtCore.QMetaObject.connectSlotsByName(top_jobs)

    def retranslateUi(self, top_jobs):
        _translate = QtCore.QCoreApplication.translate
        top_jobs.setWindowTitle(_translate("top_jobs", "Top Jobs"))
        self.label.setText(_translate("top_jobs", "The following jobs were the top matches for the profile."))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("top_jobs", "Job"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("top_jobs", "Action"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    top_jobs = QtWidgets.QDialog()
    ui = Ui_top_jobs()
    ui.setupUi(top_jobs)
    top_jobs.show()
    sys.exit(app.exec_())
