# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jobs.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Jobs(object):
    def setupUi(self, Jobs):
        Jobs.setObjectName("Jobs")
        self.jobTable.setObjectName("jobTable")
        self.jobTable.setColumnCount(2)
        self.jobTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.jobTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.jobTable.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.jobTable)
        self.goBackButton = QtWidgets.QPushButton(Jobs)
        self.goBackButton.setObjectName("goBackButton")
        self.verticalLayout.addWidget(self.goBackButton)

        self.retranslateUi(Jobs)
        QtCore.QMetaObject.connectSlotsByName(Jobs)

    def retranslateUi(self, Jobs):
        _translate = QtCore.QCoreApplication.translate
        Jobs.setWindowTitle(_translate("Jobs", "Jobs Found"))
        self.label.setText(_translate("Jobs", "The following jobs were found for:"))
        self.skill_label.setText(_translate("Jobs", "<skill>"))
        item = self.jobTable.horizontalHeaderItem(0)
        item.setText(_translate("Jobs", "Job"))
        item = self.jobTable.horizontalHeaderItem(1)
        item.setText(_translate("Jobs", "Action"))
        self.goBackButton.setText(_translate("Jobs", "Go Back"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Jobs = QtWidgets.QDialog()
    ui = Ui_Jobs()
    ui.setupUi(Jobs)
    Jobs.show()
    sys.exit(app.exec_())
