# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jobs.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Jobs(object):
    def setupUi(self, Jobs):
        Jobs.setObjectName("Jobs")
        Jobs.resize(430, 415)
        self.verticalLayout = QtWidgets.QVBoxLayout(Jobs)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Jobs)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.skill_label = QtWidgets.QLabel(Jobs)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.skill_label.setFont(font)
        self.skill_label.setObjectName("skill_label")
        self.verticalLayout.addWidget(self.skill_label)
        self.jobTable = QtWidgets.QTableWidget(Jobs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jobTable.sizePolicy().hasHeightForWidth())
        self.jobTable.setSizePolicy(sizePolicy)
        self.jobTable.setObjectName("jobTable")
        self.jobTable.setColumnCount(2)
        self.jobTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.jobTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.jobTable.setHorizontalHeaderItem(1, item)
        self.jobTable.horizontalHeader().setCascadingSectionResizes(False)
        self.jobTable.horizontalHeader().setDefaultSectionSize(200)
        self.verticalLayout.addWidget(self.jobTable)
        self.goBackButton = QtWidgets.QPushButton(Jobs)
        self.goBackButton.setObjectName("goBackButton")
        self.verticalLayout.addWidget(self.goBackButton)

        self.retranslateUi(Jobs)
        QtCore.QMetaObject.connectSlotsByName(Jobs)

    def retranslateUi(self, Jobs):
        _translate = QtCore.QCoreApplication.translate
        Jobs.setWindowTitle(_translate("Jobs", "Jobs Found"))
        self.label.setText(_translate("Jobs", "The following jobs were found for:"))
        self.skill_label.setText(_translate("Jobs", "<skill>"))
        item = self.jobTable.horizontalHeaderItem(0)
        item.setText(_translate("Jobs", "Job"))
        item = self.jobTable.horizontalHeaderItem(1)
        item.setText(_translate("Jobs", "Action"))
        self.goBackButton.setText(_translate("Jobs", "Go Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Jobs = QtWidgets.QDialog()
    ui = Ui_Jobs()
    ui.setupUi(Jobs)
    Jobs.show()
    sys.exit(app.exec_())
