# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progress_bar.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProgressBar(object):
    def setupUi(self, ProgressBar):
        ProgressBar.setObjectName("ProgressBar")
        ProgressBar.resize(280, 60)
        ProgressBar.setMinimumSize(QtCore.QSize(280, 60))
        ProgressBar.setMaximumSize(QtCore.QSize(16777215, 60))
        ProgressBar.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.verticalLayout = QtWidgets.QVBoxLayout(ProgressBar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_status = QtWidgets.QLabel(ProgressBar)
        self.lbl_status.setObjectName("lbl_status")
        self.verticalLayout.addWidget(self.lbl_status)
        self.bar_progress = QtWidgets.QProgressBar(ProgressBar)
        self.bar_progress.setProperty("value", 0)
        self.bar_progress.setObjectName("bar_progress")
        self.verticalLayout.addWidget(self.bar_progress)

        self.retranslateUi(ProgressBar)
        QtCore.QMetaObject.connectSlotsByName(ProgressBar)

    def retranslateUi(self, ProgressBar):
        _translate = QtCore.QCoreApplication.translate
        ProgressBar.setWindowTitle(_translate("ProgressBar", "Dialog"))
        self.lbl_status.setText(_translate("ProgressBar", "Loading..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProgressBar = QtWidgets.QDialog()
    ui = Ui_ProgressBar()
    ui.setupUi(ProgressBar)
    ProgressBar.show()
    sys.exit(app.exec_())
