# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skills.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LinkedInSkills(object):
    def setupUi(self, LinkedInSkills):
        LinkedInSkills.setObjectName("LinkedInSkills")
        LinkedInSkills.resize(278, 372)
        self.horizontalLayout = QtWidgets.QHBoxLayout(LinkedInSkills)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(LinkedInSkills)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 258, 352))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.skillTable = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skillTable.sizePolicy().hasHeightForWidth())
        self.skillTable.setSizePolicy(sizePolicy)
        self.skillTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.skillTable.setObjectName("skillTable")
        self.skillTable.setColumnCount(2)
        self.skillTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setHorizontalHeaderItem(1, item)
        self.skillTable.horizontalHeader().setDefaultSectionSize(119)
        self.horizontalLayout_2.addWidget(self.skillTable)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)

        self.retranslateUi(LinkedInSkills)
        QtCore.QMetaObject.connectSlotsByName(LinkedInSkills)

    def retranslateUi(self, LinkedInSkills):
        _translate = QtCore.QCoreApplication.translate
        LinkedInSkills.setWindowTitle(_translate("LinkedInSkills", "Skills"))
        item = self.skillTable.horizontalHeaderItem(0)
        item.setText(_translate("LinkedInSkills", "Skill"))
        item = self.skillTable.horizontalHeaderItem(1)
        item.setText(_translate("LinkedInSkills", "Action"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LinkedInSkills = QtWidgets.QDialog()
    ui = Ui_LinkedInSkills()
    ui.setupUi(LinkedInSkills)
    LinkedInSkills.show()
    sys.exit(app.exec_())
