# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'top_jobs.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TopJobs(object):
    def setupUi(self, TopJobs):
        TopJobs.setObjectName("TopJobs")
        TopJobs.resize(474, 372)
        self.verticalLayout = QtWidgets.QVBoxLayout(TopJobs)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(TopJobs)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(TopJobs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(238)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(TopJobs)
        QtCore.QMetaObject.connectSlotsByName(TopJobs)

    def retranslateUi(self, TopJobs):
        _translate = QtCore.QCoreApplication.translate
        TopJobs.setWindowTitle(_translate("TopJobs", "Top Jobs"))
        self.label.setText(_translate("TopJobs", "The following jobs were the top matches for the profile."))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TopJobs", "Job"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TopJobs", "Action"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TopJobs = QtWidgets.QDialog()
    ui = Ui_TopJobs()
    ui.setupUi(TopJobs)
    TopJobs.show()
    sys.exit(app.exec_())
